# Development override for docker-compose.ultimate.yml
version: '3.8'

services:
  server:
    build:
      args:
        - BUILD_ENV=development
    environment:
      - BUILD_ENV=development
      - LOG_LEVEL=DEBUG
    volumes:
      - ./hashmancer:/app/hashmancer:rw
      - ./config:/app/config:rw
    ports:
      - "8080:8080"
      - "8000:8000"
      - "5678:5678"

  worker-gpu:
    environment:
      - LOG_LEVEL=DEBUG
      - WORKER_LOG_LEVEL=DEBUG
    volumes:
      - ./hashmancer:/app/hashmancer:rw

  worker-cpu:
    environment:
      - LOG_LEVEL=DEBUG  
      - WORKER_LOG_LEVEL=DEBUG
    volumes:
      - ./hashmancer:/app/hashmancer:rw

  redis:
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 1gb --loglevel debug

networks:
  hashmancer-network:
    driver: bridge