version: "3.8"

services:
  # Redis service for caching and session management
  redis:
    image: redis:7-alpine
    container_name: hashmancer-redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - hashmancer-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp

  # Main Hashmancer server
  hashmancer:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: hashmancer-server
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-8000}:8000"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      # Core configuration
      - REDIS_URL=redis://redis:6379
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      
      # Admin configuration
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      
      # API keys (optional)
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      
      # Security settings
      - SECRET_KEY=${SECRET_KEY:-}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:8000}
      
      # Performance settings
      - MAX_WORKERS=${MAX_WORKERS:-4}
      - WORKER_TIMEOUT=${WORKER_TIMEOUT:-300}
      - MAX_UPLOAD_SIZE=${MAX_UPLOAD_SIZE:-100MB}
      
      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FORMAT=${LOG_FORMAT:-json}
    
    volumes:
      - hashmancer-data:/app/data
      - hashmancer-logs:/app/logs
      - hashmancer-config:/app/config
      - hashmancer-temp:/app/temp
      - hashmancer-uploads:/app/uploads
      
    networks:
      - hashmancer-network
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      
    security_opt:
      - no-new-privileges:true
      
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Worker service for distributed processing
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: hashmancer-worker
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      hashmancer:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
      - SERVER_URL=http://hashmancer:8000
      - WORKER_ID=${WORKER_ID:-worker-1}
      - WORKER_THREADS=${WORKER_THREADS:-4}
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    
    volumes:
      - hashmancer-worker-data:/app/data
      - hashmancer-wordlists:/app/wordlists
      - hashmancer-rules:/app/rules
      
    networks:
      - hashmancer-network
      
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
      
    security_opt:
      - no-new-privileges:true
      
    # Resource limits for worker
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '4.0'
        reservations:
          memory: 1G
          cpus: '1.0'

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: hashmancer-nginx
    restart: unless-stopped
    ports:
      - "${HTTPS_PORT:-443}:443"
      - "80:80"
    depends_on:
      - hashmancer
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/ssl:/etc/nginx/ssl:ro
      - nginx-cache:/var/cache/nginx
      - nginx-logs:/var/log/nginx
    networks:
      - hashmancer-network
    profiles:
      - nginx
    security_opt:
      - no-new-privileges:true

  # Monitoring with Prometheus (optional)
  prometheus:
    image: prom/prometheus:latest
    container_name: hashmancer-prometheus
    restart: unless-stopped
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=15d'
      - '--web.enable-lifecycle'
    networks:
      - hashmancer-network
    profiles:
      - monitoring
    security_opt:
      - no-new-privileges:true

  # Grafana for metrics visualization (optional)
  grafana:
    image: grafana/grafana:latest
    container_name: hashmancer-grafana
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana:/etc/grafana/provisioning:ro
    networks:
      - hashmancer-network
    profiles:
      - monitoring
    security_opt:
      - no-new-privileges:true

volumes:
  # Core application volumes
  redis-data:
    driver: local
  hashmancer-data:
    driver: local
  hashmancer-logs:
    driver: local
  hashmancer-config:
    driver: local
  hashmancer-temp:
    driver: local
  hashmancer-uploads:
    driver: local
  
  # Worker volumes
  hashmancer-worker-data:
    driver: local
  hashmancer-wordlists:
    driver: local
  hashmancer-rules:
    driver: local
  
  # Nginx volumes
  nginx-cache:
    driver: local
  nginx-logs:
    driver: local
  
  # Monitoring volumes
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

networks:
  hashmancer-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16