global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'hashmancer-server'
    static_configs:
      - targets: ['server:8080']
    scrape_interval: 30s
    metrics_path: '/metrics'
    
  - job_name: 'hashmancer-workers'
    static_configs:
      - targets: ['worker-gpu:8081', 'worker-cpu:8081']
    scrape_interval: 30s
    metrics_path: '/metrics'
    
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 30s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093