name: Python Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r Server/requirements.txt -r Worker/requirements.txt -r Server/requirements-dev.txt
      - name: Run flake8
        run: flake8 .
      - name: Run tests
        run: pytest -q
